name: Send App
description: Send the web applications that you want or what you have done.
title: "[Send App]: "
labels: ["send app"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to send a web application!
  - type: input
    id: appname
    attributes:
      label: App Name
      placeholder: ex. GitHub
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: Category
      placeholder: ex. Coding
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: App Description
      placeholder: ex. Is an Internet hosting service for software development and version control using Git.
    validations:
      required: true
  - type: input
    id: websiteurl
    attributes:
      label: Website URL
      placeholder: ex. https://github.com/
    validations:
      required: true
  - type: input
    id: developer
    attributes:
      label: Developer
      placeholder: ex. Microsoft
    validations:
      required: true
